### ISSUE TITLE
Edit Openers feature deletes openers

### ISSUE THREAD

**Issue by pengui** [angryziber/ipscan#23]
I just had to download version 3.3.2 (x64) after my 2.x version was deleted by my antivirus software.  In attempting to recover all of my custom openers, I noted that whatever opener I select from the "Edit openers..." feature is overwritten by whatever is in the initial opener in the list.  All other openers are now lost from my configuration, as it appears that duplicates are deleted upon clicking "Close".

1) Is there a way to reset the list back to the original defaults, and 2) is there a method for editing existing openers, if they cannot be selected in the "Edit Openers..." feature?

Thanks!

**Comment by vartaxe** [comment]
yeah just had this same issue. win 7 x64. this is very frustrating :/

**Comment by fmd-bwe** [comment]
same here. win7x64

**Comment by fmd-bwe** [comment]
Fixed as #29 
@angryziberangryziber closed this issue from a commit 2 hours ago
 @angryziber	fix #29 do not overwrite openers when moving between them in the dialog	bd4b4f8

**Comment by vartaxe** [comment]
https://sourceforge.net/p/ipscan/bugs/92/

**Comment by angryziber** [comment]
Edit Openers dialog now has the same OK/Cancel buttons as other settings dialogs, making it easy to Cacnel in case of problems.

There is another fix in master related to Up/Down buttons, soon to be released as 3.4.
Please use 3.3.3 in the mean time, which fixed most of issues in 3.3.2.
