### ISSUE TITLE
Mac vendors are max 8 chars long

### ISSUE THREAD

**Issue by beunders** [angryziber/ipscan#47]
why is the Vendor name truncated to only 8 characters ?

**Comment by angryziber** [comment]
The vendor DB is currently taken from the Wireshark project, the names are already truncated there. Can you suggest a better source?

**Comment by beunders** [comment]
No not really. I was just a bit surprised as other scanners do reveal thec omplete ID. I thought it was just a matter of reading the device. Have no personal knowledge about it.
Also noticed that when I run the scanner on a C that is connected via WiFi to the network,. that some wired devices are not being listed, while they are perfectly accessible an also react on ping messages with short delays.
Very much like the scanner and especially the speed using multiple threads.

**Comment by o5** [comment]
> Can you suggest a better source?

@angryziber I think this is the better source: http://standards-oui.ieee.org/oui.txt
