### ISSUE TITLE
it would be lovely to see the MAC Address at each IP

### ISSUE THREAD

**Issue by KayRJay** [angryziber/ipscan#55]
There are simple (enough) tools to see the MAC address for a given IP (derived from ARP).   But it sure would be nice if AngryIP Scanner could display the info per address responding to a ping.

Thanks!

**Comment by angryziber** [comment]
This feature is already available, just enable the MAC address fetcher to add this column to scanning results.

**Comment by KayRJay** [comment]
Thanks, didn’t see that.  Very helpful!
