### ISSUE TITLE
Development version: Failed to load Native Code.

### ISSUE THREAD

**Issue by celtic-bear** [angryziber/ipscan#58]
Hi, got this error without any CPU or system version logic. On my machine with Windows 10/64 32 bit version running fine, when 64 giving that error. However, on 2012R2 server this is vice versa. Tried on different 64 machines and got the same error without any logic. Tried to install on all of them the latest Java, but got the same issue.
![2012r2](https://cloud.githubusercontent.com/assets/18039771/14008112/783fda90-f1d1-11e5-8afc-68d7ea321da0.png)
![win10](https://cloud.githubusercontent.com/assets/18039771/14008158/c9c978f8-f1d1-11e5-878e-38bc1bd4e62f.png)

**Comment by angryziber** [comment]
Hello, do I understand correctly that on every machine you still get the program working, but the problem is with choosing the right build?

If this is the case, you can use the Windows Installer that tests your Java and installs the working build automatically.

**Comment by alesper3** [comment]
You misunderstand him.  He is using x86 jre. and needs to use x64jre.  Download correct jre and change run configuration to point to x64 jre instead of x86 jre.

**Comment by celtic-bear** [comment]
The problem is I was making a script, to run a scanner depending on operation system and make a log, but the problem is I can't find why x86 version is running on machines with x64 Java and not running on some others.

**Comment by alesper3** [comment]
The problem for me is when I try to run source code after building i get this:
![image](https://cloud.githubusercontent.com/assets/18506954/14945019/f2403f3e-0fcb-11e6-920b-216815c3de6e.png)
Failed to load Native Code
your answer is ok to those just running .exe, however, i would like to run the source.

**Comment by angryziber** [comment]
Please select the correct library for your platform in Project Structure (see the updated README for details).
