### ISSUE TITLE
Edit openers... deletes all Openers except Web Browser

### ISSUE THREAD

**Issue by lormanian** [angryziber/ipscan#60]
I have been running the latest version of Angry IP Scanner (v3.4.1) on my iMac running OS X v10.11.4 (15E65) since it's release and today attempted to add an Opener when I discovered a very bad, unrecoverable programming error. I wanted to add SMB to the Openers and yet regardless of the method used, i.e. right-click in results window -> Open -> Edit openers... or Menu -> Commands -> Open -> Edit openers..., simply moving the cursor down the original default list of Openers, automatically replaces them with the Web Browser and there is no way to cancel or restore the Openers. I have uninstalled the app, deleted my Trash, downloaded the latest version again, installed and executed the app from a different directory, but the app somehow remembers the automatic and erroneous deletion of all Openers, with the exception of the Web Browser and remembers my custom settings! How do I get the default Openers back? Also, most of the time when I quit the app it hangs and I must use the 'Force Quit' option. Now it is not showing the router with a green dot, it's blue; what do these dot colors represent? There is NOTHING in help or the web site to explain. I'm adding Openers, but they do not work.

**Comment by angryziber** [comment]
Thanks for reporting, I will investigate the issue.

In the mean time, you may use `rm -fr ~/.java/.userPrefs/ipscan/` to delete all stored preferences and go back to default launchers.

**Comment by angryziber** [comment]
It is interesting that the bug you are mentioning was actually present in 3.4, but was fixed in 3.4.1.
Are you sure you are running the latest version? (Check the About dialog)

Anyway, please delete all preferences and see if you still get this problem.

**Comment by lormanian** [comment]
Do you have the right person because I don't know what you are talking
about.

-Les Ormanian

**Comment by angryziber** [comment]
Isn't this the issue you have submitted?
https://github.com/angryziber/ipscan/issues/60

Anton
