### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by bellingeri** [angryziber/ipscan#63]
Hello.

I worked on the Italian translation. I try to attach it to this post not having found better method:  [messages_it.properties.zip](https://github.com/angryziber/ipscan/files/332508/messages_it.properties.zip)

I've translated the strings related to languages in each specific language (_Español_, not _Spanish_ for 'es'). I think it's a better solution than place them in english.

I also added the string [language.it=Italiano] for when the Italian will be added (I hope) in the list of available languages.

I hope I was helpful.
Thanks for your work.
Roberto.

**Comment by angryziber** [comment]
Thanks for the contribution, the translation will be available in a next release.
