### ISSUE TITLE
Error "nonexistent JRE installation" after update to Java 1.8u101

### ISSUE THREAD

**Issue by kyllan74** [angryziber/ipscan#67]
Hello.

After upgrading Java to version 1.8u101 AngryIP didn't start and displayed error message "The registry refers to nonexistent Java Runtime Environment installation or the runtime is corrupted." I've checked registry HKLM\software\JavaSoft\Java Runtime Environment" and indeed found leftover keys from Java 1.8.0_60 and 1.8.0_65. When i've deleted them, AngryIP started using correct key "1.8.0_101". Is that possible that AIP tries to find highest version and selects earlier due to sorting issue?

**Comment by angryziber** [comment]
Thanks for reporting, this is most likely a problem with Launch4j that I am
using for Windows builds, I will investigate.

**Comment by angryziber** [comment]
Fix will be released asap as 3.4.2
