### ISSUE TITLE
Text File feeder layout issue on start & modal dialogs can be positioned off-screen on Windows

### ISSUE THREAD

**Issue by anotherAdub** [angryziber/ipscan#69]
**Version:
3.4.2  August 4 2016
OS Win 7 64bit fully patched**

**Issue1: >trivial (affects usage)
Incorrect alignment of icons and buttons**

Replication:
Select "Text File" from the dropdown (no need to run) 
Close the application
Open the application

Work around:
Select another option followed by "Text File" from the dropdown to redraw the window correctly.

Images:
As opened normally. E.g. first ever opening
![bug1](https://cloud.githubusercontent.com/assets/3317265/17856424/6f22eac2-6875-11e6-815f-a725ae683a2c.png)
Display after "Text File" is selected (before it is closed/opened)
![bug2](https://cloud.githubusercontent.com/assets/3317265/17856423/6f1f5bf0-6875-11e6-90d1-ed81fa19c529.png)
Display after "Text File is selected and the application is re-opened
![bug3](https://cloud.githubusercontent.com/assets/3317265/17856425/6f241f28-6875-11e6-8604-c97c6ccd0c30.png)

**Issue2: =trivial (affects reading and closing of the about box)
Location of about box**

Replication:
Move Angry IP Scanner to the edge of the screen, especially the top, bottom or right. Select about from the help menu.

The about box does not take account of the window and so part of the about box is obscured since it is opened relative to the form.

Hope this is useful

**Comment by angryziber** [comment]
Thanks for reporting, both issues are now fixed in master and will be released soon as version 3.5

**Comment by anotherAdub** [comment]
Cool!
Great work :)
Thank you
