### ISSUE TITLE
Where is the source rpm?

### ISSUE THREAD

**Issue by ivoarch** [angryziber/ipscan#73]
Hi,
I was trying to find the source rpm but can't find it ?

Thanks in advance!

**Comment by angryziber** [comment]
Hello, there is no source rpm, as the program is written in Java and built
with Ant. However, the rpm spec is here:
https://github.com/angryziber/ipscan/blob/master/ext/rpmbuild/SPECS/ipscan.spec

**Comment by ivoarch** [comment]
Thanks!!
