### ISSUE TITLE
Greek language translation

### ISSUE THREAD

**Issue by zouloumis** [angryziber/ipscan#75]
Written by DigitalPoeter.gr

Greek language translation

Upload the file with greek translation

Waiting to make a build release with include the file for test and personal use firstly.

Waiting to receive an executable file for Windows 64bit.
[messages_gr.txt](https://github.com/angryziber/ipscan/files/543016/messages_gr.txt)

**Comment by jasonliul** [comment]
What a surprise.

**Comment by zouloumis** [comment]
@angryziber
 Waiting to receive an executable file for Windows 64bit.

**Comment by angryziber** [comment]
Version 3.5 released, thanks!
