### ISSUE TITLE
Problem Unable to launch your default browser,

### ISSUE THREAD

**Issue by stealthblue** [angryziber/ipscan#77]
Hello
I'm sorry to report such issue but I try googling as well as I spent lot of hours to solve it but I failed.
after successful scanning , I'm unable to lunch the browser directly from the Angry Ip Scanner application whether on pressing Ctrl+1 or by right click and choose   open >Web Browser.
Angry IP Scanner : version 3.4 built on Sep-6-2015
My Os is : Kali Linux lxde 64 bit 
ONLY FIREFOX INSTALLED AND NO OTHER BROWSERS
So would you kindly advice how to solve this issue.
Thanks & Regards
![angry-ip-error](https://cloud.githubusercontent.com/assets/22988510/19612370/c0b3c4f0-97ab-11e6-87f2-a6953545dcb4.png)

**Comment by angryziber** [comment]
Version 3.5 will be released soon that changed how a default browser is launched. You may want to try that. If it still doesn't work, please run ipscan from the terminal and report the output when you are trying to open the browser.
