### ISSUE TITLE
Layout Issues on Retina Displays

### ISSUE THREAD

**Issue by ikellenberger** [angryziber/ipscan#80]
On high resolution displays used on e.g. Dell XPS 9350 (13", 3200x1800px) the 'Getting Started' window is too small (and cannot be resized). The same goes for the main window, but at least this one can be resized. Additionally the icons ('Select Fetchers', 'Preferences') are too small as well.
![angryipscanner_on_high_resolution_display](https://cloud.githubusercontent.com/assets/17648070/20218976/6bf0687e-a827-11e6-8777-a5649e6e4899.png)

**Comment by angryziber** [comment]
Thanks for reporting this. Now I've got the same laptop myself, so I will definitely find time for fixing it soon.
