### ISSUE TITLE
How can i use the HTTP sender fetcher?

### ISSUE THREAD

**Issue by BeeCodiing** [angryziber/ipscan#85]
the question is in the title ^^

**Comment by angryziber** [comment]
This is actually an experimental fetcher that tests for a working HTTP proxy on port 3128.
Thanks for a reminder that it should either be removed or properly implemented.

**Comment by angryziber** [comment]
HTTPProxyFetcher was introduced that is the same as former HTTPSenderFetcher.

HTTPSenderFetcher can now be used to send any data to HTTP port 80 and parse any response out of it.
By default it makes a `HEAD /` request returning the value of `Date` header of the server. This can be configured in this fetcher's preferences.
